

// Example of an array holding data for all teams
const teamStandings = [
    {
        position: 1,
        teamName: "Bashkimi",
        matchesPlayed: 19,
        wins: 14,
        losses: 5,
        scored: 1513,
        conceded: 1370,
        goalDifference: 143,
        points: 33,
    },
    {
        position: 2,
        teamName: "	Trepça",
        matchesPlayed: 19,
        wins: 13,
        losses: 6,
        scored:1546,
        conceded:1354,
        goalDifference:192,
        points: 32,
    },
    {
        position: 3,
        teamName: "Sigal Prishtina",
        matchesPlayed: 19,
        wins: 11,
        losses: 8,
        scored: 1589,
        conceded: 1583,
        goalDifference: 6,
        points: 30,
    },
    {
        position: 4,
        teamName: "Peja",
        matchesPlayed: 	19,
        wins: 10,
        losses: 9,
        scored: 1495,
        conceded: 1457,
        goalDifference: 38,
        points: 29,
    },
    {
        position: 5,
        teamName: "Vëllaznimi",
        matchesPlayed: 19,
        wins: 10,
        losses: 9,
        scored: 1452,
        conceded: 1451,
        goalDifference: 1,
        points: 29,
    },
    {
        position: 6,
        teamName: "Golden Eagle Ylli",
        matchesPlayed: 19,
        wins: 8,
        losses: 11,
        scored: 1399,
        conceded: 1474,
        goalDifference: -75,
        points: 27,
    },
    {
        position: 7,
        teamName: "Bora",
        matchesPlayed: 19,
        wins: 6,
        losses: 13,
        scored: 1495,
        conceded: 1542,
        goalDifference: -47,
        points: 25,
    },
    {
        position: 8,
        teamName: "Proton Cable Prizreni",
        matchesPlayed: 19,
        wins: 4,
        losses: 15,
        scored: 1488,
        conceded: 1746,
        goalDifference: -258,
        points: 23,
    }

]


