export const ALL_PLAYERS_REQUEST = "ALL_PLAYERS_REQUEST";
export const ALL_PLAYERS_SUCCESS = "ALL_PLAYERS_SUCCESS";
export const ALL_PLAYERS_FAIL = "ALL_PLAYERS_FAIL";

export const PLAYER_DETAILS_REQUEST = "PLAYER_DETAILS_REQUEST";
export const PLAYER_DETAILS_SUCCESS = "PLAYER_DETAILS_SUCCESS";
export const PLAYER_DETAILS_FAIL = "PLAYER_DETAILS_FAIL";

export const CREATE_PLAYER_REQUEST = "CREATE_PLAYER_REQUEST";
export const CREATE_PLAYER_SUCCESS = "CREATE_PLAYER_SUCCESS";
export const CREATE_PLAYER_FAIL = "CREATE_PLAYER_FAIL";

export const UPDATE_PLAYER_REQUEST = "UPDATE_PLAYER_REQUEST";
export const UPDATE_PLAYER_SUCCESS = "UPDATE_PLAYER_SUCCESS";
export const UPDATE_PLAYER_FAIL = "UPDATE_PLAYER_FAIL";

export const DELETE_PLAYER_REQUEST = "DELETE_PLAYER_REQUEST";
export const DELETE_PLAYER_SUCCESS = "DELETE_PLAYER_SUCCESS";
export const DELETE_PLAYER_FAIL = "DELETE_PLAYER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";